### ISSUE TITLE
[Examples] Performance difference between gst-launch pipeline and API pipeline

### ISSUE THREAD

**Issue by boxerab** [nnstreamer/nnstreamer#1082]
I am using tensorflow and tensorflow lite on CPU, Ubuntu 18.

The command line example 
```
gst-launch-1.0 textoverlay name=overlay font-desc="Sans, 26" ! \
    videoconvert ! ximagesink name=img_test \
    v4l2src name=cam_src ! videoconvert ! videoscale ! video/x-raw,width=640,height=480,format=RGB ! \
    tee name=t_raw \
    t_raw. ! queue ! overlay.video_sink \
    t_raw. ! queue ! videoscale ! video/x-raw,width=224,height=224 ! \
    tensor_converter ! \
    tensor_filter framework=tensorflow-lite \
    model=tflite_model/mobilenet_v1_1.0_224_quant.tflite ! \
    tensor_decoder mode=image_labeling \
    option1=tflite_model/labels.txt ! \
    overlay.text_sink
```
is many times slower than

`./nnstreamer_example_image_classification  `

with dropped buffers.  Is there any reason why the speed is so different ?

**Comment by myungjoo** [comment]
It is because ```tflite_model/mobilenet_v1_1.0_224_quant.tflite``` cannot process at the rate the camera is giving. You need to drop older frames to make it **"LOOK FAST"**. (it's not actually fast if the memory overhead of large queues can be neglected)

By dropping older frames, you can let the "filter" always use most recent frame, easily synchronizing with the recent camera frames.
