### ISSUE TITLE
ML C-API related to tensor data and info is not thread safe

### ISSUE THREAD

**Issue by kparichay** [nnstreamer/nnstreamer#2600]
Although the single and pipeline related C-API is thread safe, tensor data and info related API is not thread.
Example - parallel calls to ml_tensors_info_destroy() or ml_tensors_data_destroy() can result in undefined behavior.

**Comment by myungjoo** [comment]
As we've discussed, we need to measure the expected overhead (latency) of locking mechanisms for info create/destroy because some users may call them too frequently. They are expected to use simple pipelines if they are going to call single API frequently, but as you already know, they do the unexpected every time.

This is release critical, but let's assume that this is for Tizen 6.5, not 6.0.

**Comment by kparichay** [comment]
Also as discussed, apart from thread safety, ownership of data object to be transferred to single/pipeline object when operating on it also needs to be done for Tizen 6.5 release.

**Comment by myungjoo** [comment]
@kparichay Is this issue still valid?

**Comment by kparichay** [comment]
The issue is still valid, as operations on `ml_tensors_info_h` or `ml_tensors_data_h` (create/destroy) are not thread safe. 
IMO, adding documentation stating that these operations are not thread-safe can be step 1. 
Adding support for thread-safe comes at a cost which needs to be analyzed before the implementation as mentioned in https://github.com/nnstreamer/nnstreamer/issues/2600#issuecomment-666433003.

**Comment by myungjoo** [comment]
My proposal:

**Default. Public API's behavior**: add a lock per each instance of ml_tensors_info and ml_tensors_data
**Optional. "Performance mode internal users' behavior"**: run without such locks.

I'll add a PR that does this for ml_tensors_info
