### ISSUE TITLE
model file example for python and cpp filter plugins

### ISSUE THREAD

**Issue by giladnahor** [nnstreamer/nnstreamer#2694]
Hi,
Can you please share an example model files for the tensor_filter_python.cc and tensor_filter_cpp.cc frameworks?
Thanks a lot!

**Comment by myungjoo** [comment]
tensor_filter_cpp: https://github.com/nnstreamer/nnstreamer/tree/master/tests/cpp_methods

python:
- app code: https://github.com/nnstreamer/nnstreamer/tree/master/tests/nnstreamer_filter_python
- py model: https://github.com/nnstreamer/nnstreamer/blob/master/tests/test_models/models/passthrough.py

**Comment by myungjoo** [comment]
Because we intend to have at least one test case for each feature, trying to achieve unit test coverage over 80%, every feature is expected to have an example at ```/tests/```. 

In many cases, if you want to embed your own code into a pipeline as a filter, "custom-easy" is enough. For that, you may refer to https://github.com/nnstreamer/nnstreamer-example/blob/master/native/example_repo_custom_easy/example_repo_custom_easy.cc (LINE 168, 180, 234, 237)
