### ISSUE TITLE
error: format string is not a string literal [-Werror,-Wformat-nonliteral]

### ISSUE THREAD

**Issue by javyxu** [nnstreamer/nnstreamer#2725]
System Version:
Catalina: Apple clang version 12.0.0 (clang-1200.0.26.2)
conda的 virtual envriments：python3.7.9

![image](https://user-images.githubusercontent.com/22185273/92989862-045e7a00-f50a-11ea-92fd-4995ab7bb8c3.png)

**Comment by myungjoo** [comment]
It appears that you are using VERY OLD opencv (opencv2). Try to disable opencv2 completely or upgrade opencv (opencv3 or 4)

OpenCV3 was released 5 years ago and we usually use OpenCV4 these days.


Because nnstreamer does NOT depend on opencv, but a few test cases of nnstreamer depend on opencv. Thus, you may add ```-Denable-test=false``` to meson, which disables building all test cases, if you do not want to update opencv to modern versions.

**Comment by javyxu** [comment]
> It appears that you are using VERY OLD opencv (opencv2). Try to disable opencv2 completely or upgrade opencv (opencv3 or 4)
> 
> OpenCV3 was released 5 years ago and we usually use OpenCV4 these days.
> 
> Because nnstreamer does NOT depend on opencv, but a few test cases of nnstreamer depend on opencv. Thus, you may add `-Denable-test=false` to meson, which disables building all test cases, if you do not want to update opencv to modern versions.

Hello, I modified the code in the test file, now it is ok, thank you

**Comment by myungjoo** [comment]
Could you please share how you have modified?

We may disable opencv usages in test cases if the given opencv at build-time is too old.

**Comment by javyxu** [comment]
> Could you please share how you have modified?
> 
> We may disable opencv usages in test cases if the given opencv at build-time is too old.

Hello, I'm modifying the header file of these two files:
![image](https://user-images.githubusercontent.com/22185273/93016990-030b7b00-f5f8-11ea-9415-ab2ddd71364d.png)
![image](https://user-images.githubusercontent.com/22185273/93017011-1ae2ff00-f5f8-11ea-9289-837ec280baca.png)
