### ISSUE TITLE
[Android/tf-lite] The current version has a pipeline error for Android build.

### ISSUE THREAD

**Issue by davichiar** [nnstreamer/nnstreamer#2779]
=========================================================================
(1). Pipeline error in
nnstreamer-example/android/example_app/nnstreamer-media-ssd/
nnstreamer-example/tree/master/android/example_app/nnstreamer-multi/
nnstreamer-example/tree/master/android/example_app/nnstreamer-ssd

Android based on commit version aae799f6f480fd88edb48987bc25001521ab5c0e. [Error : Failed to build pipeline [1]]
Logcat Error : Unable to build pipeline: could not link tensortransform0 to tensor filter 0

=========================================================================
(2) If you build with this commit version 6b27767fc0af96dcfd7dd3f84eef215bd50a7aaa, resolve some of these errors.
nnstreamer-example/android/example_app/nnstreamer-media-ssd/ (pipeline error)
nnstreamer-example/tree/master/android/example_app/nnstreamer-multi/ (no error)
nnstreamer-example/tree/master/android/example_app/nnstreamer-ssd (pipeline error)

=========================================================================
(3) I don't know why this error occurs, but because we only need nnstreamer-multi,
we're using it in 6b27767fc0af96dcfd7dd3f84eef215bd50a7aaa commit versions.

Because of this, create a bug report.

**Comment by myungjoo** [comment]
@gichan-jang @anyj0527 Can one of you review the bug report?

**Comment by anyj0527** [comment]
Sorry for late.
I checked the reported https://github.com/nnstreamer/nnstreamer/commit/aae799f6f480fd88edb48987bc25001521ab5c0e and current main branch with [tflite-1.13.1](https://github.com/nnstreamer/nnstreamer-android-resource/blob/master/external/tensorflow-lite-1.13.1.tar.xz), and those apps with both commit are running well. The pipeline error was might because of wrong tflite library but I'm not sure.
