### ISSUE TITLE
Supporting pipelined HW - separate input and output callback 

### ISSUE THREAD

**Issue by giladnahor** [nnstreamer/nnstreamer#2791]
Hi guys.
I'm integrating our HW accelerator into nnstreamer.
In order to reach high performance I need different callbacks running in separate threads for handling input and output tasks.
Our HW accelerator is pipelined, using the current invoke() function I must send the data to be inferenced to our HW wait for it to finish and only than I can return from the invoke function and handle next frame.
I want to have a separate function for sending the output data.
This way I can use the invoke function to send the frame to our HW and immediately return to handle the next frame.
In the background I'll have another thread getting the inference from our HW, once it is ready sending it to the output pads.
Is this function supported in nnstreamer?
If not is there a simple way to allow it?

Love your project and looking forward for future collaboration.
Thanks a lot!

**Comment by myungjoo** [comment]
I haven't experienced such methods directly. However, what I've heard from gstreamer developers years ago working on hardware pipelines might be helpful.

1. Express each stage of hardware pipeline as a filter
2. The output of non-final-stage filter simply signals "DONE" (other/tensors, 1:1:1:1, uint8 ?), triggering the action of next stage of the hardware pipieline or simply showing that the next stage is started.
3. The output of final-stage filter fetches the actual output.

E.g.,
HARDWARE: (all the hardware pieces are connected via direct wire so that they may send data without DRAM access)
```
[ CAMERA ] --> [ IMAGE PROCESSOR HW ] --> [ PICTURE QUALITY ENHANCER HW ] --> [ COLOR SPACE CONVERTER HW ] --> [ RESIZE HW ACCELERATOR ] --> [ DRAM ]
```
GST PIPELINE:
```
CamCTL ! ImageProcCTL ! PQECTL ! ACC_COL ! ACC_RESIZE
```
Each "CTL" and "ACC" filters simply signals the "next" filter to do the next task.

**Comment by myungjoo** [comment]
@dongju-chae @wooksong : You may need similar approaches for your projects as well.

**Comment by myungjoo** [comment]
Another random idea:

You may want to write a "gst-bin" so that you can encapsule such a set of elements and treat them as a single element for easier usage (sort of syntactic sugar)

**Comment by myungjoo** [comment]
Yet another random idea:

If you really want to create the whole thing as a single tensor-filter subplugin, your filter subplugin may generate a "dummy" output with initial input fillings.

For example, if you have 3 pipeline stages, starting from an empty hw pipeline,

T0: input frame 0 arrived
T1: input frame 0 processed at stage 0. Subplugin provides a dummy output so that tensor-filter may fetch the next input frame. --> input frame 1 arrived
T2: input frame 0 processed at stage 1, input frame 1 processed at stage 0. Subplugin provides a dummy output so that tensor-filter may fetch the next input frame. --> input frame 2 arrived.
T3: input frame 0 processed at stage 2, ready for output. input frame 1 processed at stage 1, input frame 2 processed at stage 0. Subplugin finally provides a real output from input frame 0

You will simply need to provide some mechanism to drop such "dummy" outputs after tensor-fitler (a simple custom filter should suffice)

With this approach, you can keep providing a single tensor-filter subplugin, which helps programmability.

**Comment by myungjoo** [comment]
> In the background I'll have another thread getting the inference from our HW, once it is ready sending it to the output pads.
> Is this function supported in nnstreamer?

If you want to do it, you may generate a dummy output whenever a new input frame may be accepted so that a new input frame can be accepted.

Anyway, you need to:
1. ensure that the dummy output is ignored or not accepted by later elements
2. ensure that the actual output is pushed to later elements afterwards even when there is no next input frame. (this part is not trivially supported by tensor-filter subplugin structure; that is why I've thought about generating dummy inputs)

**Comment by giladnahor** [comment]
Hi,
Thanks for all the ideas.
I think that the best suited one is to separate to 2 filters for "send" and "receive" data to our HW.
This will also allow me to send 'metadata' between the 2 filters "above" our HW.
Does nnstreamer support per payload metadata? Do you have an example?

The issue is that I need to initialize our HW on one filter and send the "context" and data structures to the other filter.
Is it possible if I wrap it all with a gst-bin? Never tried it before.
Thanks!
________________________________

**Comment by myungjoo** [comment]
> The issue is that I need to initialize our HW on one filter and send the "context" and data structures to the other filter.
Is it possible if I wrap it all with a gst-bin? Never tried it before.

I guess you may have a global data structure representing HW status and refer to that one (a pointer or resource id) with the "context" shared between filters. I don't think you need gst-bin for such and gst-bin won't be helpful for such.

**Comment by myungjoo** [comment]
Closing this because as there is no more follow-up discussions.
