### ISSUE TITLE
Test Coverage Dropped. Need to Add Test Cases

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#2882]
It is dropped to 77.8% !!! Need more test cases.

Although protobuf/flatbuf generated files are included, we should cover them with proper protobuf/flatbuf test cases.
(Do not exclude them!)

![image](https://user-images.githubusercontent.com/1109011/99649260-54703480-2a97-11eb-92e4-999d814c183d.png)

**Comment by dongju-chae** [comment]
Well.. I think we have to exclude protobuf/flatbuf generated files because they have not being tested correctly.
For example, they look like
```
     Line data    Source code
       1             : /* EOF */
       2             : /* EOF */
       3             : /* EOF */
       4             : /* EOF */
       5             : /* EOF */
       6             : /* EOF */
       7             : /* EOF */
       8             : /* EOF */
       9             : /* EOF */
      10             : /* EOF */
      11             : /* EOF */
      12             : /* EOF */
      13             : /* EOF */
      14             : /* EOF */
      15             : /* EOF */
      16             : /* EOF */
      17             : /* EOF */
      18             : /* EOF */
      19             : /* EOF */
      20             : /* EOF */
      21             : /* EOF */
      22             : /* EOF */
      23             : /* EOF */
      24             : /* EOF */
```

Also, they are generated on each object file, which are often duplicated. So, I think it's better to exclude them from coverage analysis (PR: https://github.com/nnstreamer/nnstreamer/pull/2909) until we resolve this issue.

**Comment by dongju-chae** [comment]
Now, the coverage is 81.1% :)
