### ISSUE TITLE
Broken Links in Documentation 

### ISSUE THREAD

**Issue by dongju-chae** [nnstreamer/nnstreamer#3100]
We recently constructed `nnstreamer.github.io` to serve hotdoc-generated html files.
But, the problem is that `github.com` now have missing links in docs.

I think the main cause is that html files in `nnstreamer.github.io` have referenced each other using a sub-directory, `Documentation`.
- https://nnstreamer.github.io/Documentation/coding-convention.html

`meson` can be good reference.
- https://mesonbuild.com/Builtin-options.html
- https://github.com/mesonbuild/meson/blob/master/docs/markdown/Builtin-options.md

**Comment by JuYeong0413** [comment]
Since there are two `Contributing` pages in `nnstreamer.github.io`, how about combining them to `CONTRIBUTING.md` in the root directory?

<img src="https://user-images.githubusercontent.com/33684401/109251338-9b0bc280-782e-11eb-91d6-1cdd77e9b99d.png" width="30%">

Referencing `CODE_OF_CONDUCT.md` from `Documentation/` will break the link, but referencing files in `Documentation/` from the root won't make problems.

**Comment by dongju-chae** [comment]
Other docs also have similar problems. For example, 
 - https://github.com/nnstreamer/nnstreamer/blob/main/Documentation/how-to-use-testcases.md

**Comment by gichan-jang** [comment]
We want to meet two things in `github` and `github.io`.
 1. Link will not break.
 2. Move from `github.io` to a sub-page of the `github.io`, not `github`.

These two requirements cannot be met because documents located in different locations cross-referenced.
To resolve this problem
 1. Change archive (Place the documents in the same directory)
 2. Remove link to other locations
 3. Not preferred, but there's a way to write down the URL. #3103 

Which one is better?

**Comment by dongju-chae** [comment]
Let's close this as this topic was almost resolved.
