### ISSUE TITLE
[BBox] process BBox with 

### ISSUE THREAD

**Issue by kevinbingsong** [nnstreamer/nnstreamer#3222]
Suggest to process BBox with gst_buffer_add_video_region_of_interest_meta(). You can refer below code. So platform can process with HW if HW can do it.

https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad/-/commit/f71eb2949772176a68ae5217cc94ae4d75a8ae95#5d8823b45ea728077b138db0566c6154837bf7fd_0_642

**Comment by myungjoo** [comment]
@gichan-jang @helloahn @jaeyun-jung @wooksong : Is anyone of you interested in this?

**Comment by kimjh12** [comment]
@kevinbingsong I looked into your code but I still don't get how you can exploit HW accel..? Could you give us more detailed description about this? Besides, this might require our filter pipeline to be altered

**Comment by myungjoo** [comment]
@kimjh12 : Please share your conclusions regarding this topic.

**Comment by kimjh12** [comment]
I guess the main advantage of using VideoRegionOfInterestMeta is that you can stream bbox along with hardware video acceleration formats like VA-API. Currently since we don't use gst-meta for inner implementations and we support bbox decoder that composite with raw output, that might involve quite heavy engineering.
We will consider that feature as a part of further roadmap and get onto it if the regarding requirements are specified.

**Comment by myungjoo** [comment]
@kevinbingsong Are you interested in implementing and contributing this feature?
I'll close this issue. Please reopen (or let me know) if you or someone else volunteers to implement.
