### ISSUE TITLE
How to merge and reshape tensor

### ISSUE THREAD

**Issue by fast-xun** [nnstreamer/nnstreamer#3808]
I am a student, testing yolov3 model.
It has three outputs(1 * 255 * 13 * 13, 1 * 255 * 26 * 26, 1 * 255 * 52 * 52).I want to merge them and reshape.(Because the tensor_decoder needs tensor whose shape is [85, 13 * 13 * 3 + 26 * 26 * 3 + 52 * 52 * 3, 1])
I don't know if there is an off-the-shelf element that can do this.

I'd appreciate it if you could help me.Thank you in advance. :)

**Comment by anyj0527** [comment]
The `tensor_decoder mode=bounding_boxes option1=yolov5 ...` assume a [85, 10647, 1] dim output if the model is yolov5 model for 416 x 416 image.

There is no off-the-shelf element for process those three output to be required shape.
You may modify your yolov3 model so that its output to be a single tensor,
or make a new tensor_decoder for yolo models whose output come up with three tensors ("anchor"s).

REF: https://github.com/nnstreamer/nnstreamer/pull/3628 (This is the PR for the yolov5 decoder)

**Comment by myungjoo** [comment]
You need to describe how such tensors are to be reshaped. If you can describe it with basic arithmetic operators, transpose,a nd such, you can describe it with tensor_split, tensor_merge, and tensor_transform. .... so how these tensors are supposed to be "reduced" into smaller dimensions?

**Comment by myungjoo** [comment]
With no further following-up questions or discussions, I assume this is completed.
