### ISSUE TITLE
tensor-decoder / bounding-box

### ISSUE THREAD

**Issue by myungjoo** [nnstreamer/nnstreamer#4104]
Issues:
- [ ] The available options must be fully described in the top comment sections.
    https://github.com/nnstreamer/nnstreamer/blob/2144d9963fc5136cc71bdb3d2287159bb217921f/ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c#L30-L100
- [ ] The available options should be fully visible to the shell users w/ nnstreamer-check.

**Comment by brandall25** [comment]
@myungjoo Hello, thanks for posting this. I'm new to this project and looking to contribute.

Could you be more specific about what you want added to the comments? It seems as though all the existing options are accounted for.

**Comment by myungjoo** [comment]
https://github.com/nnstreamer/nnstreamer/blob/bc55e86c6b8bce7b788100560b0ea5f9aab4e0cb/ext/nnstreamer/tensor_decoder/tensordec-boundingbox.c#L181-L194

```ov-face-detection``` and ```mp-palm-detection``` are missing.

**Comment by brandall25** [comment]
@myungjoo I've added the missing networks to the description, however I'm not sure how to `gst-inspect` the bounding boxes plugin. Furthermore, I'm not sure how to modify `tensordec-boundingbox.c` so that `gst-inspect` can read it and display the right info.

When I run `gst-inspect-1.0 nnstreamer tensor_decoder`, I see that there is a `bounding_boxes` subplugin, but I'm not sure how to access it.

I've tried `gst-inspect-1.0 nnstreamer tensor_decoder/bounding_boxes` and few other variations.

**Comment by myungjoo** [comment]
You may add messages for nnstreamer-check.

For example, tensor_filter subplugins uses ```nnstreamer_filter_set_custom_property_desc```:
https://github.com/nnstreamer/nnstreamer/blob/9b2f840e2c2883c5ac1e04138341677955dcda9e/ext/nnstreamer/tensor_filter/tensor_filter_edgetpu.cc#L558-L564

Similarly, tensor_decoder subplugins may use ```nnstreamer_decoder_set_custom_property_desc```:
https://github.com/nnstreamer/nnstreamer/blob/9b2f840e2c2883c5ac1e04138341677955dcda9e/gst/nnstreamer/include/nnstreamer_plugin_api_decoder.h#L123-L127

**Comment by myungjoo** [comment]
This will be resolved by #4288
