### ISSUE TITLE
Make timestamp (and potentially other metadata) available for python3 tensor_filter?

### ISSUE THREAD

**Issue by bveldhoen** [nnstreamer/nnstreamer#4524]
Hello,

It would be helpful if the gstreamer timestamp (and potentially other metadata) would be available for CustomFilter implementations used in python3 tensor_filter.

Is there a way to get the timestamp of (a) tensor(s) in the python3 implementation? Or are there any plans to add this functionality?

**Comment by myungjoo** [comment]
I do not have a plan to provide timestamp for custom filters becauase I didn't even know that it is needed.

Anyway, GSTBUF has timestamp information; thus, we will need to open up an interface to access GSTBUF for tensor_filter's subplugins and customfilters. Right now, we do not provide such interfaces and subplugins (including python3) get the striped input buffers (without anything related to metadata of GSTBUF).

For such capabilities, tensor_filter's APIs might need some rework. I'd like to suggest:
1. add a property "supply-timestamp=1 | 0" to tensor_fitler
2. update the base class, "tensor_filter_subplugin" c++ class:
```
virtual void invoke (const GstTensorMemory *input, GstTensorMemory *output) = 0;
```
==>
```
virtual void invoke (const GstTensorMemory *input, GstTensorMemory *output) = 0;
virtual void invoke (const GstTensorMemory *input, GstTensorMemory *output, const GstTensorBufferMetadata *meta) {
  invoke(input, output);
}
```
and let invoke (input, output, meta) called instead of invoke (input, output) if ```supply-timestamp = 1```.
```
typedef struct {
  GstClockTime *pts;
  GstClockTime *dts;
  GstClockTime *duration;
  // May be extended in the future
  // Everything will be freed after invoke() is returned.
} meta; // suggestion only.
```
3. supporting tensor-filter subplugin will override invoke(input, output, meta) function. (i.e., python3).

**Comment by bveldhoen** [comment]
@myungjoo Thanks for your feedback, the proposed changes seem good.

I assume there will be a python class corresponding to GstTensorBufferMetadata, which will be made available in the python tensor_filter CustomFilter implementation(s)?

**Comment by jaeyun-jung** [comment]
suggestion : adding timestamp info into GstTensorFilterProperties
invoke function of filter subplugin has GstTensorFilterProperties arg, so it is easy to pass information.
