### ISSUE TITLE
Does nnstreamer support Qualcomm/SNPE Ubuntu?

### ISSUE THREAD

**Issue by edwardnguyen1705** [nnstreamer/nnstreamer#4579]
Hi @anyj0527,
I have been looking for gstreamer-based framework for AI model inference, and`nnstreamer` looks very promising. I have searched in this repo (sourcecode, issues), I am not sure whether`nnstreamer` supports Qualcomm/SNPE Ubuntu or not, and if there is any available example, I would like to check.

**Comment by anyj0527** [comment]
NNStreamer with QC/SNPE has been tested in host linux / tizen aarch64 / android devices. I expect it would work well in your target. When you test your target, provide a proper pkg-config file `snpe.pc` to build nnstreamer with snpe support.

Check some unittests using snpe filter here: https://github.com/nnstreamer/nnstreamer/blob/main/tests/nnstreamer_filter_snpe/unittest_filter_snpe.cc

**Comment by myungjoo** [comment]
Because it is built and used in Tizen and Android, there is no reason Ubuntu is incompatible w/ SNPE, AFAIK.

So please go ahead: build and test it.
You will need to install snpe (along with headers and .pc file desginating where snpe is installed) and enable snpe-build as a meson option. For available meson options, please refer to meson_options.txt file.

**Comment by edwardnguyen1705** [comment]
Thanks you @anyj0527 and @myungjoo for the info.
