### ISSUE TITLE
[RunTest] fake USB camera for NNStreamer video apps

### ISSUE THREAD

**Issue by leemgs** [nnstreamer/nnstreamer#531]
* Background:
In order to test video streaming data, We need to attache a USB camera to Ubunut PC. In case that the Ubunut PC does not have any USB camera, We need to get appropriate approach to fix this situation. 
Let's try to support a fake video-loopback device for a Ubuntu server that does not have a USB video camera device.

* ci/taos/plugins-staging/pr-nnstreamer-ubuntu-apptest.sh
   * https://github.com/nnsuite/TAOS-CI/pull/191
```bash
# Test with sample apps
    # @todo We have to modify the commented test files below 
        because this script requires a USB camera device.
```

* Wiki Page (as a instruction manual)
   * https://github.com/nnsuite/nnstreamer/wiki/usage-examples-screenshots

CC/ @jaeyun-jung , @ohsewon  PTAL.

**Comment by leemgs** [comment]
From my survey, fake USB camera operation will be hlepful to us.  So,  I will try survy how to enable a loopback device driver for a **virtual** Camera device driver in more detail. I think that we can stream a display ( as a fake USB camera ) that is showed in our Ubuntu PC. If we can do it, We do not need to modify the exising source code that is written for a sample application.

**Comment by leemgs** [comment]
```
invain@mymate:~/nnstreamer/bin$ ./nnstreamer_example_filter
** Message: start app..
** Message: finished to load labels, total 1001
** Message: received start message
** Message: received error message
ERROR: from element /GstPipeline:pipeline0/GstV4l2Src:cam_src: Internal data flow error.
Additional debug info:
gstbasesrc.c(2948): gst_base_src_loop (): /GstPipeline:pipeline0/GstV4l2Src:cam_src:
streaming task paused, reason not-negotiated (-4)
** Message: close app..
invain@mymate:~/nnstreamer/bin$ 

```

**Comment by leemgs** [comment]
* Producer: 
   * $ gst-launch-1.0 videotestsrc ! v4l2sink device=/dev/video0
   * $ gst-launch-1.0 videotestsrc ! video/x-raw,width=640,height=480 ! v4l2sink device=/dev/video0

**Comment by jaeyun-jung** [comment]
After merging PR #551

fake cam
$ gst-launch-1.0 videotestsrc ! v4l2sink device=/dev/video0

and then run filter example
$ ./nnstreamer_example_filter

**Comment by leemgs** [comment]
## Summary for running Camera apps with Loopback Camera devicedriver
```bash

* Example app:  nnstreamer environment: 
https://github.com/nnsuite/nnstreamer/wiki/usage-examples-screenshots

 export NNST_ROOT=$HOME/nnstreamer  # set your own path to install libs and header files
 export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NNST_ROOT/lib
 export GST_PLUGIN_PATH=$GST_PLUGIN_PATH:$NNST_ROOT/lib


* debugging
GST_DEBUG_NO_COLOR=1 GST_DEBUG=xv*:5 gst-launch-0.10 videotestsrc !  xvimagesink 
gst-inspect-1.0 xvimagesink

git clone  https://github.com/umlaeute/v4l2loopback.git
$ make && sudo make install
$ sudo depmod -a

* kernel module 
modprobe v4l2loopback
lsmod | grep v4l2

* producer
ffmpeg -f x11grab -r 15 -s 1280x720 -i :0.0+0,0 -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video0
gst-launch-1.0 videotestsrc ! v4l2sink device=/dev/video0

* consumer
gst-launch-1.0 v4l2src device=/dev/video0 ! xvimagesink
./nnstreamer_example_filter

```

**Comment by leemgs** [comment]
* How to run GUI application in terminal client (for just test gui application)
```
$ sudo apt-get install tightvncserver vlc
$ Xvnc :1 &
$ wget http://www.engr.colostate.edu/me/facil/dynamics/files/bird.avi
$ DISPLAY="0.0:1" vlc drop.avi
```

**Comment by leemgs** [comment]
@ohsewon PTAL, Please start a activity to append this technique to the existing NNStreamer apptest (CI Module).

**Comment by myungjoo** [comment]
> $ gst-launch-1.0 videotestsrc ! v4l2sink device=/dev/video0

Obviously, you cannot do this. /dev/video0 is not an output (sink) device.

> $ gst-launch-1.0 v4l2src device=/dev/video0 ! xvimagesink

1. If you are doing this in X remotely, use ximagesink instead of xvimagesink
2. Add videoconvert between v4l2src and ximagesink. It may be using incompatible protocols.

**Comment by leemgs** [comment]
@ohsewon  In order to run GUI application of NNStreamer, please try to utilize Xvnc.

**Comment by ohsewon** [comment]
Solved.
```bash
$ sudo modprobe v4l2loopback
$ Xvnc :0 
$ export NNST_ROOT=$HOME/nnstreamer  # set your own path to install libs and header files
$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NNST_ROOT/lib
$ export GST_PLUGIN_PATH=$GST_PLUGIN_PATH:$NNST_ROOT/lib

change authority of /dev/video0 for all.

$ gst-launch-1.0 videotestsrc ! v4l2sink device=/dev/video0 &
$ ./nnstreamer_example_filter
```

**Comment by leemgs** [comment]
Done

**Comment by mchehab** [comment]
I had some discussions with v4l2 gstreamer with regards to v4l2loopback out of tree driver. Despite all problems it has with the Kernel driver (with made me reject upstream Kernel submissions), it has also two issues that affect gstreamer, because v4l2loopback is not compliant with V4L2 API, thus requiring specific hacks at the pipelines for it to hopefully work:

1) it can't use more than 2 request buffers, as otherwide v4l2loopback produces frames with wrong IDs;
2) allocation queries should be prevented by adding "! identity drop-allocation=1! " to the pipeline.

So, don't use v4l2loopback, as it won't help to test real cameras scenarios.

Instead, there are two alternatives:

1) Use the Kernel driver vivid. This is a virtual V4L2 device with is v4l2-compliant. It can simulate a large variety of device types, depending on the modprobed parameters. Its documentation is at:
   https://linuxtv.org/downloads/v4l-dvb-apis-new/v4l-drivers/vivid.html
This driver comes with an image generator. The image produced by it can be controlled via standard V4L2 controls via a V4L2 application, like v4l2-ctl and qv4l2 (both are part of v4l-utils, although Tizen currently doesn't build them).
2) Use a mem2mem driver. There are some drivers for Exynos and other SoC that have hardware encoders/decoders/image transform capabilities.

On a m2m device, the same file descriptor should be used for both capture and output, so it should be a single pipeline with both source and sink entities.

Also, with a m2m driver, gstreamer, by default, expects that the input format to be different than the output format. if the format is the same, it just do an image pass-though, without actually using the m2m driver. So, an extra parameter is required to force the pass-trough mode (disable-passthough). E. g. on such case, the pipeline would be somethng like:

$ gst-launch-1.0 videotestsrc ! v4l2video0convert disable-passthrough=1 ! videoconvert ! ximagesink

It should be noticed that the disable-passtrough parameter is new (added after 1.14.4), so it has to be backported to the gstreamer version used at the tests.

There is also a very simple driver called vim2m. It could, in thesis be used with the above pipeline. However, it uses an input format that currently is not compatible with gstreamer (RGB 565 BE). I'm working on a Kernel patch to solve this issue.

**Comment by myungjoo** [comment]
One of us (@nnsuite/nnstreamer ) will be able to look at this issue after 2/15 (1902A) unless the current production goes faster than expected. Thanks.

**Comment by mchehab** [comment]
I added some fixes to vim2m driver. It should now work fine in order to emulate a camera. The Kernel patches are on my development tree:

    https://git.linuxtv.org/mchehab/experimental.git/log/?h=vim2m

With that, it is possible to use, for example, a *.mp4 file to simulate a camera:
$ gst-launch-1.0 filesrc      location=some_camera_compressed_file.mp4 ! decodebin ! videoconvert ! video/x-raw,format=RGB ! v4l2video0convert disable-passthrough=1 extra-controls="s,horizontal_flip=1,vertical_flip=1" ! video/x-raw,format=RGB16 ! videoconvert ! ximagesink

**Comment by myungjoo** [comment]
Close this if it's done. @leemgs
